databases:
  - name: researchcollab-db
    plan: free
    databaseName: researchcollab_db

services:
  - type: web
    name: researchcollab
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn researchcollab.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: researchcollab-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.9"

